// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./components/views/About.vue')['default']
    About_bk: typeof import('./components/views/About_bk.vue')['default']
    Blog: typeof import('./components/views/Blog.vue')['default']
    CardItemComponent: typeof import('./components/Common/CardItemComponent.vue')['default']
    CreateBlog: typeof import('./components/views/CreateBlog.vue')['default']
    EditorImage: typeof import('./components/Tinymce/components/EditorImage.vue')['default']
    Footer: typeof import('./components/Common/Footer.vue')['default']
    Header: typeof import('./components/Common/Header.vue')['default']
    Home: typeof import('./components/views/Home.vue')['default']
    HomeApp: typeof import('./components/HomeApp.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    LeftMenu: typeof import('./components/Common/LeftMenu.vue')['default']
    LoginComponent: typeof import('./components/views/LoginComponent.vue')['default']
    MenuMobileComponent: typeof import('./components/Common/MenuMobileComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollTop: typeof import('./components/Common/ScrollTop.vue')['default']
    SlideBarComponent: typeof import('./components/Common/SlideBarComponent.vue')['default']
    SocialLogin: typeof import('./components/Common/SocialLogin.vue')['default']
    Tinymce: typeof import('./components/Tinymce/index.vue')['default']
  }
}

export {}
